export const AppRoute = {
    HOME_SCREEN: 'HOME_SCREEN',
    KARAOKE_SCREEN: 'KARAOKE_SCREEN',
    PERSONAL_SCREEN: 'PERSONAL_SCREEN',
    RADIO_SCREEN: 'RADIO_SCREEN',
    SHORT_COVER_SCREEN: 'SHORT_COVER_SCREEN'
}